name: Post Cuelinks Deals to Telegram

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}
  schedule:
    - cron: "0 */6 * * *"   # every 6 hours auto run

jobs:
  post-deals:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run bot
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHANNEL_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}
          CUELINKS_TOKEN: ${{ secrets.CUELINKS_TOKEN }}
          MAX_POSTS: '5'
        run: python main.py
        
